/**
 * tracking.server.ts — the forward-tested ledger for soccer and tennis.
 *
 * WHY THIS EXISTS WHEN THERE ARE ALREADY BACKTESTS
 * ------------------------------------------------
 * A backtest can be re-run until it looks good. Even done honestly — walk
 * forward, hold out seasons, pre-register the ablations — the person running it
 * chooses when to stop, and every choice they make is informed by data that has
 * already happened. That is not a character flaw, it is the structure of the
 * exercise.
 *
 * A row written the morning of a match cannot be improved afterwards. So this
 * module does one thing: record what the model said BEFORE the event, then come
 * back later and score it. `UNIQUE (model_version, event_id)` in the schema is
 * what enforces it — a prediction is inserted once and never overwritten, so a
 * later run cannot quietly upgrade an earlier call.
 *
 * The ledger starts EMPTY, and it will stay uninformative for months. That is
 * not a defect to be hidden behind a backtest number; the Track Record pages
 * show both, labelled, and say plainly when the live sample is too small to
 * mean anything. A tracking page that quietly falls back to the backtest when
 * it has no data would be worse than no tracking page.
 *
 * NFL and NBA already have Track Record pages, but those replay history and
 * score it retroactively — a backtest in a track record's clothing. They can be
 * wired into this ledger the same way; the writer below is sport-agnostic.
 */

import { supabaseAdmin as _admin } from "@/integrations/supabase/client.server";
import { supabase } from "@/integrations/supabase/client";
import { LEAGUES, type LeagueSlug } from "./soccer-leagues";
import { TOURS, type TourSlug } from "./tennis-tours";
import { bucketise, type Bucket } from "./ledger-stats";
import { predictSlate } from "./espn.server";
import { soccerSlate } from "./soccer.server";
import { tennisSlate } from "./tennis.server";

/** Bumped when a model changes in a way that makes old rows incomparable. */
export const SOCCER_MODEL_VERSION = "soccer-elo-gd-v1";
export const TENNIS_MODEL_VERSION = "tennis-logistic-no-h2h-v1";
/**
 * NFL and NBA use the same Elo-with-market-blend that builds their daily slate.
 * They had Track Record pages long before this ledger existed, but those pages
 * replayed finished seasons and scored them afterwards — a backtest wearing a
 * track record's name. These versions mark the rows that are the real thing.
 */
export const NFL_MODEL_VERSION = "nfl-elo-market-v1";
export const NBA_MODEL_VERSION = "nba-elo-market-v1";

export type Outcome = "a" | "draw" | "b";

/** Which model's rows belong to a sport. */
export function modelVersionFor(sport: string): string {
  if (sport === "soccer") return SOCCER_MODEL_VERSION;
  if (sport === "tennis") return TENNIS_MODEL_VERSION;
  if (sport === "nfl") return NFL_MODEL_VERSION;
  return NBA_MODEL_VERSION;
}

export type LedgerRow = {
  sport: string;
  division: string;
  model_version: string;
  event_id: string;
  event_date: string;
  subject_a: string;
  subject_b: string;
  context: string | null;
  prob_a: number;
  prob_draw: number | null;
  prob_b: number;
  pick: Outcome;
  pick_prob: number;
  result: Outcome | null;
  correct: boolean | null;
  brier: number | null;
  log_loss: number | null;
  rps: number | null;
  final_score: string | null;
  settled_at: string | null;
  predicted_at: string;
  provenance?: "forward" | "reconstructed";
};

/**
 * The generated Supabase types do not know about event_predictions — that file
 * is regenerated by tooling and hand-edits get clobbered. The cast is confined
 * to these two helpers rather than sprayed across the module.
 */
type AnyTable = {
  from: (t: string) => any; // eslint-disable-line @typescript-eslint/no-explicit-any
};
const admin = () => _admin as unknown as AnyTable | undefined;

/**
 * Reads prefer the service-role client and fall back to the public one.
 *
 * Both work — the table is world-readable — but the public client resolves its
 * URL through `import.meta.env`, which only exists once Vite has processed the
 * module. In a plain Node context (a script, a test) touching it throws before
 * the `process.env` fallback is reached. Preferring the server client means the
 * read path does not depend on which bundler happened to load it.
 */
const reader = () => admin() ?? (supabase as unknown as AnyTable);

export function canTrack(): boolean {
  return Boolean(_admin);
}

// ------------------------------------------------------------------ scoring

/**
 * Score one settled prediction.
 *
 * Brier is the multiclass form (sum of squared errors over every outcome) so a
 * two-way and a three-way market land on the same scale and can sit in the same
 * table. RPS is three-way only, because it needs the outcomes to be ordered —
 * home > draw > away is an ordering; player A > player B is not.
 */
export function scoreOutcome(
  probs: { a: number; draw: number | null; b: number },
  result: Outcome,
) {
  const three = probs.draw != null;
  const vec = three ? [probs.a, probs.draw!, probs.b] : [probs.a, probs.b];
  const keys: Outcome[] = three ? ["a", "draw", "b"] : ["a", "b"];
  const truth = keys.map((k) => (k === result ? 1 : 0));

  const brier = vec.reduce((s, p, i) => s + (p - truth[i]) ** 2, 0);
  const pAct = Math.min(1 - 1e-9, Math.max(1e-9, vec[keys.indexOf(result)]));
  const logLoss = -Math.log(pAct);

  let rps: number | null = null;
  if (three) {
    let cp = 0;
    let cy = 0;
    let acc = 0;
    for (let i = 0; i < vec.length - 1; i += 1) {
      cp += vec[i];
      cy += truth[i];
      acc += (cp - cy) ** 2;
    }
    rps = acc;
  }
  return { brier, logLoss, rps };
}

const pickOf = (probs: { a: number; draw: number | null; b: number }): Outcome => {
  const d = probs.draw ?? -1;
  if (probs.a >= d && probs.a >= probs.b) return "a";
  if (probs.b >= d) return "b";
  return "draw";
};

// ------------------------------------------------------------------- write

/**
 * Insert rows, ignoring any that already exist.
 *
 * A prediction is written once. Re-running the cron on the same day must not
 * change yesterday's call, so conflicts on (model_version, event_id) are
 * dropped rather than merged — that is the whole guarantee this table offers.
 */
async function insertNew(rows: Partial<LedgerRow>[]): Promise<number> {
  const db = admin();
  if (!db || rows.length === 0) return 0;
  const { error, count } = await db
    .from("event_predictions")
    .upsert(rows, { onConflict: "model_version,event_id", ignoreDuplicates: true, count: "exact" });
  if (error) {
    console.error("[tracking] insert failed:", error.message);
    return 0;
  }
  return count ?? 0;
}

/** Record every priced soccer fixture for a date, across all five leagues. */
export async function snapshotSoccer(date: string): Promise<number> {
  let written = 0;
  for (const l of LEAGUES) {
    try {
      const slate = await soccerSlate(l.slug as LeagueSlug, date);
      const rows = slate.matches
        // Unpriced fixtures are not predictions; a promoted club with no rating
        // has nothing to be right or wrong about.
        .filter((m) => m.probs != null)
        .map((m) => {
          const probs = { a: m.probs!.home, draw: m.probs!.draw, b: m.probs!.away };
          const pick = pickOf(probs);
          return {
            sport: "soccer",
            division: l.slug,
            model_version: SOCCER_MODEL_VERSION,
            event_id: m.id,
            event_date: date,
            subject_a: m.home.name,
            subject_b: m.away.name,
            context: m.venue || null,
            prob_a: probs.a,
            prob_draw: probs.draw,
            prob_b: probs.b,
            pick,
            pick_prob: pick === "a" ? probs.a : pick === "draw" ? probs.draw : probs.b,
          };
        });
      written += await insertNew(rows);
    } catch (err) {
      console.error(`[tracking] soccer ${l.slug} ${date}:`, err);
    }
  }
  return written;
}

/** Record every priced tennis match for a date, across both tours. */
export async function snapshotTennis(date: string): Promise<number> {
  let written = 0;
  for (const t of TOURS) {
    try {
      const slate = await tennisSlate(t.slug as TourSlug, date);
      const rows = slate.matches
        .filter((m) => m.probA != null)
        .map((m) => {
          const probs = { a: m.probA!, draw: null, b: 1 - m.probA! };
          const pick = pickOf(probs);
          return {
            sport: "tennis",
            division: t.slug,
            model_version: TENNIS_MODEL_VERSION,
            event_id: m.id,
            event_date: date,
            subject_a: m.a.name,
            subject_b: m.b.name,
            context: [m.tournament, m.round, m.surface].filter(Boolean).join(" · ") || null,
            prob_a: probs.a,
            prob_draw: null,
            prob_b: probs.b,
            pick,
            pick_prob: pick === "a" ? probs.a : probs.b,
          };
        });
      written += await insertNew(rows);
    } catch (err) {
      console.error(`[tracking] tennis ${t.slug} ${date}:`, err);
    }
  }
  return written;
}

/**
 * Record every priced NFL or NBA game for a date.
 *
 * `predictSlate` is exactly what the daily slate page renders, so what gets
 * written down is what a reader was shown that morning — which is the only
 * version of this worth storing. A game already in progress or finished is
 * skipped: a "prediction" made after first pitch is not one.
 */
export async function snapshotTeamSport(sport: "nfl" | "nba", date: string): Promise<number> {
  const version = sport === "nfl" ? NFL_MODEL_VERSION : NBA_MODEL_VERSION;
  try {
    const { games } = await predictSlate(sport, date);
    const rows = games
      .filter((g) => g.winner == null && g.homeScore == null)
      .map((g) => {
        const probs = { a: g.homeWinProb, draw: null, b: g.awayWinProb };
        const pick = pickOf(probs);
        return {
          sport,
          division: sport,
          model_version: version,
          event_id: String(g.gameId),
          event_date: date,
          subject_a: g.home.name,
          subject_b: g.away.name,
          context: g.venue || null,
          prob_a: probs.a,
          prob_draw: null,
          prob_b: probs.b,
          pick,
          pick_prob: pick === "a" ? probs.a : probs.b,
        };
      });
    return await insertNew(rows);
  } catch (err) {
    console.error(`[tracking] ${sport} ${date}:`, err);
    return 0;
  }
}

// ------------------------------------------------------------------ settle

/**
 * Score every unsettled prediction whose event has finished.
 *
 * Rows are grouped by (sport, division, date) so one slate fetch settles a whole
 * day rather than one match. Anything still unresolved — postponed, walkover,
 * not yet played — is simply left pending and picked up next run.
 */
export async function settlePending(throughDate: string, lookbackDays = 21) {
  const db = admin();
  if (!db) return { settled: 0, pending: 0 };

  const since = new Date(`${throughDate}T00:00:00Z`);
  since.setUTCDate(since.getUTCDate() - lookbackDays);
  const from = since.toISOString().slice(0, 10);

  const { data, error } = await db
    .from("event_predictions")
    .select("id, sport, division, event_id, event_date, prob_a, prob_draw, prob_b, pick")
    .is("settled_at", null)
    .gte("event_date", from)
    .lte("event_date", throughDate);
  if (error) {
    console.error("[tracking] settle read failed:", error.message);
    return { settled: 0, pending: 0 };
  }
  const pending = (data ?? []) as {
    id: number;
    sport: string;
    division: string;
    event_id: string;
    event_date: string;
    prob_a: number;
    prob_draw: number | null;
    prob_b: number;
    pick: Outcome;
  }[];
  if (pending.length === 0) return { settled: 0, pending: 0 };

  // One slate call per (sport, division, date).
  const groups = new Map<string, typeof pending>();
  for (const r of pending) {
    const k = `${r.sport}|${r.division}|${r.event_date}`;
    groups.set(k, [...(groups.get(k) ?? []), r]);
  }

  let settled = 0;
  for (const [key, rows] of groups) {
    const [sport, division, date] = key.split("|");
    try {
      const outcomes = new Map<string, { result: Outcome; score: string }>();
      if (sport === "soccer") {
        const s = await soccerSlate(division as LeagueSlug, date);
        for (const m of s.matches) {
          if (!m.result) continue;
          outcomes.set(m.id, {
            result: m.result === "H" ? "a" : m.result === "A" ? "b" : "draw",
            score: `${m.homeGoals}-${m.awayGoals}`,
          });
        }
      } else if (sport === "tennis") {
        const s = await tennisSlate(division as TourSlug, date);
        for (const m of s.matches) {
          if (!m.winner) continue;
          outcomes.set(m.id, { result: m.winner, score: m.scoreline || "" });
        }
      } else {
        // NFL and NBA. "a" is always the home side, matching the snapshot.
        const { games } = await predictSlate(sport as "nfl" | "nba", date);
        for (const g of games) {
          if (!g.winner) continue;
          outcomes.set(String(g.gameId), {
            result: g.winner === "home" ? "a" : "b",
            score: `${g.homeScore ?? ""}-${g.awayScore ?? ""}`,
          });
        }
      }

      const now = new Date().toISOString();
      for (const r of rows) {
        const o = outcomes.get(r.event_id);
        if (!o) continue;
        const probs = {
          a: Number(r.prob_a),
          draw: r.prob_draw == null ? null : Number(r.prob_draw),
          b: Number(r.prob_b),
        };
        const { brier, logLoss, rps } = scoreOutcome(probs, o.result);
        const { error: uErr } = await db
          .from("event_predictions")
          .update({
            result: o.result,
            correct: r.pick === o.result,
            brier,
            log_loss: logLoss,
            rps,
            final_score: o.score || null,
            settled_at: now,
          })
          .eq("id", r.id);
        if (uErr) console.error(`[tracking] settle ${r.id}:`, uErr.message);
        else settled += 1;
      }
    } catch (err) {
      console.error(`[tracking] settle ${key}:`, err);
    }
  }
  return { settled, pending: pending.length - settled };
}

/** One full cycle: record today and tomorrow, then score what has finished. */
export async function runTrackingCycle(today: string) {
  const tomorrow = new Date(`${today}T00:00:00Z`);
  tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);
  const next = tomorrow.toISOString().slice(0, 10);

  const soccer = (await snapshotSoccer(today)) + (await snapshotSoccer(next));
  const tennis = (await snapshotTennis(today)) + (await snapshotTennis(next));
  const nfl = (await snapshotTeamSport("nfl", today)) + (await snapshotTeamSport("nfl", next));
  const nba = (await snapshotTeamSport("nba", today)) + (await snapshotTeamSport("nba", next));
  const settled = await settlePending(today);
  return { today, recorded: { soccer, tennis, nfl, nba }, ...settled };
}

// -------------------------------------------------------------------- read

export type LedgerSummary = {
  n: number;
  correct: number;
  accuracy: number | null;
  brier: number | null;
  logLoss: number | null;
  rps: number | null;
  pending: number;
  firstDate: string | null;
  lastDate: string | null;
};

/**
 * Why the ledger is empty, when it is.
 *
 * "Nothing settled yet" and "the table this reads from does not exist" look
 * identical on a page that only counts rows, and they could not be more
 * different: one resolves itself by waiting, the other never does. The ledger
 * sat empty for weeks because `event_predictions` had never been created and
 * the read error was swallowed, so the page kept promising data on "the next
 * daily cycle" that no cycle was ever going to write.
 */
export type LedgerStatus =
  /** The table is there and was read. Zero rows means zero rows. */
  | "ok"
  /** The table does not exist — the migration has not been applied. */
  | "not-provisioned"
  /** It exists but could not be read: credentials, permissions, network. */
  | "unreadable";

export type LedgerView = {
  sport: string;
  division: string;
  modelVersion: string;
  status: LedgerStatus;
  /** Whether this process could write to the ledger at all. */
  writable: boolean;
  /** Which kind of row this view counted. Never a mix of the two. */
  provenance: "forward" | "reconstructed";
  summary: LedgerSummary;
  /** Accuracy in probability bands — the calibration check that matters. */
  calibration: Bucket[];
  /** Most recent settled calls, newest first. */
  recent: LedgerRow[];
  /**
   * Cumulative accuracy over settled predictions, oldest to newest.
   *
   * Carries the date and a running Brier alongside, because a hit rate that
   * drifts is only interesting next to WHEN it drifted and whether the
   * probabilities drifted with it. `n` is the sample behind each point, which
   * is what makes the early wobble readable rather than alarming.
   */
  running: { i: number; date: string; accuracy: number; brier: number }[];
  /** One row per day the ledger settled anything, oldest first. */
  daily: { date: string; n: number; correct: number; accuracy: number; brier: number }[];
};

/**
 * Read one slice of the ledger.
 *
 * `provenance` is a required decision rather than an optional filter, because
 * there is no correct way to read both at once. Forward rows were written
 * before their events and reconstructed rows were replayed afterwards; a single
 * accuracy over the union of the two would be a number with no meaning, and the
 * more rows the backfill adds the more thoroughly it would drown the real
 * record. Callers ask for one or the other and the page labels what it got.
 */
export async function readLedger(
  sport: string,
  division: string,
  provenance: "forward" | "reconstructed" = "forward",
): Promise<LedgerView> {
  const modelVersion = modelVersionFor(sport);
  const empty: LedgerView = {
    sport,
    division,
    modelVersion,
    status: "ok",
    writable: canTrack(),
    provenance,
    summary: {
      n: 0,
      correct: 0,
      accuracy: null,
      brier: null,
      logLoss: null,
      rps: null,
      pending: 0,
      firstDate: null,
      lastDate: null,
    },
    calibration: [],
    recent: [],
    running: [],
    daily: [],
  };

  try {
    const { data, error } = await reader()
      .from("event_predictions")
      .select("*")
      .eq("sport", sport)
      .eq("division", division)
      .eq("model_version", modelVersion)
      // Rows written before the provenance column existed are forward rows:
      // the backfill is the only thing that has ever written anything else.
      .or(
        provenance === "forward"
          ? "provenance.eq.forward,provenance.is.null"
          : "provenance.eq.reconstructed",
      )
      .order("event_date", { ascending: false })
      .limit(5000);
    if (error) {
      // PGRST205 is PostgREST for "no such table". Distinguishing it from every
      // other read failure is the whole point of the status field: this one is
      // a deployment step nobody ran, and no amount of waiting fixes it.
      const missing =
        (error as { code?: string }).code === "PGRST205" ||
        /Could not find the table/i.test(error.message ?? "");
      console.error(
        missing
          ? "[tracking] event_predictions does not exist — apply supabase/migrations/20260815120000_event_predictions.sql"
          : `[tracking] read failed: ${error.message}`,
      );
      return { ...empty, status: missing ? "not-provisioned" : "unreadable" };
    }
    const rows = (data ?? []) as LedgerRow[];
    const settled = rows.filter((r) => r.settled_at && r.result);
    const pending = rows.length - settled.length;
    if (settled.length === 0) {
      return { ...empty, status: "ok", summary: { ...empty.summary, pending } };
    }

    const n = settled.length;
    const correct = settled.filter((r) => r.correct).length;
    const mean = (f: (r: LedgerRow) => number | null) => {
      const vals = settled.map(f).filter((v): v is number => v != null);
      return vals.length ? vals.reduce((a, b) => a + b, 0) / vals.length : null;
    };
    const dates = settled.map((r) => r.event_date).sort();

    // Shared with the replayed history and with NFL/NBA, so the confidence
    // buckets on every Track Record page mean the same thing.
    const calibration = bucketise(
      settled.map((r) => ({ pickProb: Number(r.pick_prob), correct: Boolean(r.correct) })),
    );

    // Oldest first, so the running series reads left to right like a chart.
    const chrono = [...settled].reverse();
    let hits = 0;
    let brierSum = 0;
    const running = chrono.map((r, i) => {
      hits += r.correct ? 1 : 0;
      brierSum += Number(r.brier ?? 0);
      return {
        i: i + 1,
        date: r.event_date,
        accuracy: hits / (i + 1),
        brier: brierSum / (i + 1),
      };
    });

    // Per-day aggregates. A day with one settled call is noisy on its own but
    // is what makes the volume of the ledger visible, which is the honest
    // context for every other number on the page.
    const byDay = new Map<string, { n: number; correct: number; brier: number }>();
    for (const r of chrono) {
      const d = byDay.get(r.event_date) ?? { n: 0, correct: 0, brier: 0 };
      d.n += 1;
      d.correct += r.correct ? 1 : 0;
      d.brier += Number(r.brier ?? 0);
      byDay.set(r.event_date, d);
    }
    const daily = [...byDay.entries()]
      .sort((a, b) => a[0].localeCompare(b[0]))
      .map(([date, d]) => ({
        date,
        n: d.n,
        correct: d.correct,
        accuracy: d.correct / d.n,
        brier: d.brier / d.n,
      }));

    return {
      sport,
      division,
      modelVersion,
      status: "ok",
      writable: canTrack(),
      provenance,
      summary: {
        n,
        correct,
        accuracy: correct / n,
        brier: mean((r) => (r.brier == null ? null : Number(r.brier))),
        logLoss: mean((r) => (r.log_loss == null ? null : Number(r.log_loss))),
        rps: mean((r) => (r.rps == null ? null : Number(r.rps))),
        pending,
        firstDate: dates[0] ?? null,
        lastDate: dates[dates.length - 1] ?? null,
      },
      calibration,
      recent: settled.slice(0, 50),
      running,
      daily,
    };
  } catch (err) {
    console.error("[tracking] read threw:", err);
    return { ...empty, status: "unreadable" };
  }
}
