/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as NflRouteImport } from './routes/nfl'
import { Route as NbaRouteImport } from './routes/nba'
import { Route as ModelRouteImport } from './routes/model'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BestOddsRouteImport } from './routes/best-odds'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksRunPipelineRouteImport } from './routes/api/public/hooks/run-pipeline'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const NflRoute = NflRouteImport.update({
  id: '/nfl',
  path: '/nfl',
  getParentRoute: () => rootRouteImport,
} as any)
const NbaRoute = NbaRouteImport.update({
  id: '/nba',
  path: '/nba',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BestOddsRoute = BestOddsRouteImport.update({
  id: '/best-odds',
  path: '/best-odds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunPipelineRoute =
  ApiPublicHooksRunPipelineRouteImport.update({
    id: '/api/public/hooks/run-pipeline',
    path: '/api/public/hooks/run-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/best-odds': typeof BestOddsRoute
  '/history': typeof HistoryRoute
  '/model': typeof ModelRoute
  '/nba': typeof NbaRoute
  '/nfl': typeof NflRoute
  '/teams': typeof TeamsRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/best-odds': typeof BestOddsRoute
  '/history': typeof HistoryRoute
  '/model': typeof ModelRoute
  '/nba': typeof NbaRoute
  '/nfl': typeof NflRoute
  '/teams': typeof TeamsRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/best-odds': typeof BestOddsRoute
  '/history': typeof HistoryRoute
  '/model': typeof ModelRoute
  '/nba': typeof NbaRoute
  '/nfl': typeof NflRoute
  '/teams': typeof TeamsRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/best-odds'
    | '/history'
    | '/model'
    | '/nba'
    | '/nfl'
    | '/teams'
    | '/api/public/hooks/run-pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/best-odds'
    | '/history'
    | '/model'
    | '/nba'
    | '/nfl'
    | '/teams'
    | '/api/public/hooks/run-pipeline'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/best-odds'
    | '/history'
    | '/model'
    | '/nba'
    | '/nfl'
    | '/teams'
    | '/api/public/hooks/run-pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BestOddsRoute: typeof BestOddsRoute
  HistoryRoute: typeof HistoryRoute
  ModelRoute: typeof ModelRoute
  NbaRoute: typeof NbaRoute
  NflRoute: typeof NflRoute
  TeamsRoute: typeof TeamsRoute
  ApiPublicHooksRunPipelineRoute: typeof ApiPublicHooksRunPipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfl': {
      id: '/nfl'
      path: '/nfl'
      fullPath: '/nfl'
      preLoaderRoute: typeof NflRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nba': {
      id: '/nba'
      path: '/nba'
      fullPath: '/nba'
      preLoaderRoute: typeof NbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-odds': {
      id: '/best-odds'
      path: '/best-odds'
      fullPath: '/best-odds'
      preLoaderRoute: typeof BestOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-pipeline': {
      id: '/api/public/hooks/run-pipeline'
      path: '/api/public/hooks/run-pipeline'
      fullPath: '/api/public/hooks/run-pipeline'
      preLoaderRoute: typeof ApiPublicHooksRunPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BestOddsRoute: BestOddsRoute,
  HistoryRoute: HistoryRoute,
  ModelRoute: ModelRoute,
  NbaRoute: NbaRoute,
  NflRoute: NflRoute,
  TeamsRoute: TeamsRoute,
  ApiPublicHooksRunPipelineRoute: ApiPublicHooksRunPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
