/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as NflRouteImport } from './routes/nfl'
import { Route as NbaRouteImport } from './routes/nba'
import { Route as ModelRouteImport } from './routes/model'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BestOddsRouteImport } from './routes/best-odds'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NflIndexRouteImport } from './routes/nfl.index'
import { Route as NbaIndexRouteImport } from './routes/nba.index'
import { Route as NflTrackRecordRouteImport } from './routes/nfl.track-record'
import { Route as NflRecommendedRouteImport } from './routes/nfl.recommended'
import { Route as NflBestOddsRouteImport } from './routes/nfl.best-odds'
import { Route as NbaTrackRecordRouteImport } from './routes/nba.track-record'
import { Route as NbaRecommendedRouteImport } from './routes/nba.recommended'
import { Route as NbaBestOddsRouteImport } from './routes/nba.best-odds'
import { Route as ApiPublicHooksRunPipelineRouteImport } from './routes/api/public/hooks/run-pipeline'

const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const NflRoute = NflRouteImport.update({
  id: '/nfl',
  path: '/nfl',
  getParentRoute: () => rootRouteImport,
} as any)
const NbaRoute = NbaRouteImport.update({
  id: '/nba',
  path: '/nba',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelRoute = ModelRouteImport.update({
  id: '/model',
  path: '/model',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BestOddsRoute = BestOddsRouteImport.update({
  id: '/best-odds',
  path: '/best-odds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NflIndexRoute = NflIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NflRoute,
} as any)
const NbaIndexRoute = NbaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NbaRoute,
} as any)
const NflTrackRecordRoute = NflTrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => NflRoute,
} as any)
const NflRecommendedRoute = NflRecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => NflRoute,
} as any)
const NflBestOddsRoute = NflBestOddsRouteImport.update({
  id: '/best-odds',
  path: '/best-odds',
  getParentRoute: () => NflRoute,
} as any)
const NbaTrackRecordRoute = NbaTrackRecordRouteImport.update({
  id: '/track-record',
  path: '/track-record',
  getParentRoute: () => NbaRoute,
} as any)
const NbaRecommendedRoute = NbaRecommendedRouteImport.update({
  id: '/recommended',
  path: '/recommended',
  getParentRoute: () => NbaRoute,
} as any)
const NbaBestOddsRoute = NbaBestOddsRouteImport.update({
  id: '/best-odds',
  path: '/best-odds',
  getParentRoute: () => NbaRoute,
} as any)
const ApiPublicHooksRunPipelineRoute =
  ApiPublicHooksRunPipelineRouteImport.update({
    id: '/api/public/hooks/run-pipeline',
    path: '/api/public/hooks/run-pipeline',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/best-odds': typeof BestOddsRoute
  '/history': typeof HistoryRoute
  '/model': typeof ModelRoute
  '/nba': typeof NbaRouteWithChildren
  '/nfl': typeof NflRouteWithChildren
  '/teams': typeof TeamsRoute
  '/nba/best-odds': typeof NbaBestOddsRoute
  '/nba/recommended': typeof NbaRecommendedRoute
  '/nba/track-record': typeof NbaTrackRecordRoute
  '/nfl/best-odds': typeof NflBestOddsRoute
  '/nfl/recommended': typeof NflRecommendedRoute
  '/nfl/track-record': typeof NflTrackRecordRoute
  '/nba/': typeof NbaIndexRoute
  '/nfl/': typeof NflIndexRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/best-odds': typeof BestOddsRoute
  '/history': typeof HistoryRoute
  '/model': typeof ModelRoute
  '/teams': typeof TeamsRoute
  '/nba/best-odds': typeof NbaBestOddsRoute
  '/nba/recommended': typeof NbaRecommendedRoute
  '/nba/track-record': typeof NbaTrackRecordRoute
  '/nfl/best-odds': typeof NflBestOddsRoute
  '/nfl/recommended': typeof NflRecommendedRoute
  '/nfl/track-record': typeof NflTrackRecordRoute
  '/nba': typeof NbaIndexRoute
  '/nfl': typeof NflIndexRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/best-odds': typeof BestOddsRoute
  '/history': typeof HistoryRoute
  '/model': typeof ModelRoute
  '/nba': typeof NbaRouteWithChildren
  '/nfl': typeof NflRouteWithChildren
  '/teams': typeof TeamsRoute
  '/nba/best-odds': typeof NbaBestOddsRoute
  '/nba/recommended': typeof NbaRecommendedRoute
  '/nba/track-record': typeof NbaTrackRecordRoute
  '/nfl/best-odds': typeof NflBestOddsRoute
  '/nfl/recommended': typeof NflRecommendedRoute
  '/nfl/track-record': typeof NflTrackRecordRoute
  '/nba/': typeof NbaIndexRoute
  '/nfl/': typeof NflIndexRoute
  '/api/public/hooks/run-pipeline': typeof ApiPublicHooksRunPipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/best-odds'
    | '/history'
    | '/model'
    | '/nba'
    | '/nfl'
    | '/teams'
    | '/nba/best-odds'
    | '/nba/recommended'
    | '/nba/track-record'
    | '/nfl/best-odds'
    | '/nfl/recommended'
    | '/nfl/track-record'
    | '/nba/'
    | '/nfl/'
    | '/api/public/hooks/run-pipeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/best-odds'
    | '/history'
    | '/model'
    | '/teams'
    | '/nba/best-odds'
    | '/nba/recommended'
    | '/nba/track-record'
    | '/nfl/best-odds'
    | '/nfl/recommended'
    | '/nfl/track-record'
    | '/nba'
    | '/nfl'
    | '/api/public/hooks/run-pipeline'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/best-odds'
    | '/history'
    | '/model'
    | '/nba'
    | '/nfl'
    | '/teams'
    | '/nba/best-odds'
    | '/nba/recommended'
    | '/nba/track-record'
    | '/nfl/best-odds'
    | '/nfl/recommended'
    | '/nfl/track-record'
    | '/nba/'
    | '/nfl/'
    | '/api/public/hooks/run-pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BestOddsRoute: typeof BestOddsRoute
  HistoryRoute: typeof HistoryRoute
  ModelRoute: typeof ModelRoute
  NbaRoute: typeof NbaRouteWithChildren
  NflRoute: typeof NflRouteWithChildren
  TeamsRoute: typeof TeamsRoute
  ApiPublicHooksRunPipelineRoute: typeof ApiPublicHooksRunPipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfl': {
      id: '/nfl'
      path: '/nfl'
      fullPath: '/nfl'
      preLoaderRoute: typeof NflRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nba': {
      id: '/nba'
      path: '/nba'
      fullPath: '/nba'
      preLoaderRoute: typeof NbaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model': {
      id: '/model'
      path: '/model'
      fullPath: '/model'
      preLoaderRoute: typeof ModelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-odds': {
      id: '/best-odds'
      path: '/best-odds'
      fullPath: '/best-odds'
      preLoaderRoute: typeof BestOddsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nfl/': {
      id: '/nfl/'
      path: '/'
      fullPath: '/nfl/'
      preLoaderRoute: typeof NflIndexRouteImport
      parentRoute: typeof NflRoute
    }
    '/nba/': {
      id: '/nba/'
      path: '/'
      fullPath: '/nba/'
      preLoaderRoute: typeof NbaIndexRouteImport
      parentRoute: typeof NbaRoute
    }
    '/nfl/track-record': {
      id: '/nfl/track-record'
      path: '/track-record'
      fullPath: '/nfl/track-record'
      preLoaderRoute: typeof NflTrackRecordRouteImport
      parentRoute: typeof NflRoute
    }
    '/nfl/recommended': {
      id: '/nfl/recommended'
      path: '/recommended'
      fullPath: '/nfl/recommended'
      preLoaderRoute: typeof NflRecommendedRouteImport
      parentRoute: typeof NflRoute
    }
    '/nfl/best-odds': {
      id: '/nfl/best-odds'
      path: '/best-odds'
      fullPath: '/nfl/best-odds'
      preLoaderRoute: typeof NflBestOddsRouteImport
      parentRoute: typeof NflRoute
    }
    '/nba/track-record': {
      id: '/nba/track-record'
      path: '/track-record'
      fullPath: '/nba/track-record'
      preLoaderRoute: typeof NbaTrackRecordRouteImport
      parentRoute: typeof NbaRoute
    }
    '/nba/recommended': {
      id: '/nba/recommended'
      path: '/recommended'
      fullPath: '/nba/recommended'
      preLoaderRoute: typeof NbaRecommendedRouteImport
      parentRoute: typeof NbaRoute
    }
    '/nba/best-odds': {
      id: '/nba/best-odds'
      path: '/best-odds'
      fullPath: '/nba/best-odds'
      preLoaderRoute: typeof NbaBestOddsRouteImport
      parentRoute: typeof NbaRoute
    }
    '/api/public/hooks/run-pipeline': {
      id: '/api/public/hooks/run-pipeline'
      path: '/api/public/hooks/run-pipeline'
      fullPath: '/api/public/hooks/run-pipeline'
      preLoaderRoute: typeof ApiPublicHooksRunPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NbaRouteChildren {
  NbaBestOddsRoute: typeof NbaBestOddsRoute
  NbaRecommendedRoute: typeof NbaRecommendedRoute
  NbaTrackRecordRoute: typeof NbaTrackRecordRoute
  NbaIndexRoute: typeof NbaIndexRoute
}

const NbaRouteChildren: NbaRouteChildren = {
  NbaBestOddsRoute: NbaBestOddsRoute,
  NbaRecommendedRoute: NbaRecommendedRoute,
  NbaTrackRecordRoute: NbaTrackRecordRoute,
  NbaIndexRoute: NbaIndexRoute,
}

const NbaRouteWithChildren = NbaRoute._addFileChildren(NbaRouteChildren)

interface NflRouteChildren {
  NflBestOddsRoute: typeof NflBestOddsRoute
  NflRecommendedRoute: typeof NflRecommendedRoute
  NflTrackRecordRoute: typeof NflTrackRecordRoute
  NflIndexRoute: typeof NflIndexRoute
}

const NflRouteChildren: NflRouteChildren = {
  NflBestOddsRoute: NflBestOddsRoute,
  NflRecommendedRoute: NflRecommendedRoute,
  NflTrackRecordRoute: NflTrackRecordRoute,
  NflIndexRoute: NflIndexRoute,
}

const NflRouteWithChildren = NflRoute._addFileChildren(NflRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BestOddsRoute: BestOddsRoute,
  HistoryRoute: HistoryRoute,
  ModelRoute: ModelRoute,
  NbaRoute: NbaRouteWithChildren,
  NflRoute: NflRouteWithChildren,
  TeamsRoute: TeamsRoute,
  ApiPublicHooksRunPipelineRoute: ApiPublicHooksRunPipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
